package main

//go:generate goen example.go

// AccountBalanceType .
//goen:values
//CLOSING_AVAILABLE
//CLOSING_BOOKED
//CLOSING_CLEARED
//EXPECTED
//FORWARD_AVAILABLE
//INFORMATION
//INTERIM_AVAILABLE
//INTERIM_BOOKED
//INTERIM_CLEARED
//OPENING_AVAILABLE
//OPENING_BOOKED
//OPENING_CLEARED
//PREVIOUSLY_CLOSED_BOOKED
//AUTHORISED
//OTHER
//UNKNOWN
type AccountBalanceType uint8

// AccountIdentificationType .
//goen:values
//SORT_CODE
//ACCOUNT_NUMBER
//IBAN
//BBAN
//BIC
//PAN
//MASKED_PAN
//MSISDN
//BSB
//NCC
//ABA
//ABA_WIRE
//ABA_ACH
//EMAIL
type AccountIdentificationType uint8
